apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: custom-ginkgo-executor
  namespace: testkube
spec:
  args:
  - -vv
  command:
  - ginkgo
  content_types:
  - string
  - file-uri
  - git-file
  - git-dir
  - git
  executor_type: job
  features:
  - artifacts
  - junit-report
  image: kubeshop/testkube-ginkgo-executor:1.16.20
  meta:
    docsURI: https://kubeshop.github.io/testkube/test-types/executor-ginkgo
    iconURI: ginkgo
  types:
  - ginkgo/test
  job_template: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      name: ssljob
    spec:
      template:
        spec:
          containers:
          - name: test-container
            image: kubeshop/testkube-ginkgo-executor:1.16.20
            command: ["ginkgo"]
            args: ["-vv"]
            volumeMounts:
            - name: ssl
              mountPath: /etc/ssl/certs
          volumes:
          - name: ssl
            configMap:
              name: ca-bundle
