apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaUser
metadata:
  name: testkube-consumer
  namespace: testkube
spec:
  clusterRef:
    name: kafka-brokers
    namespace: kafka-brokers
  createCert: true
  dnsNames:
  - testkube-consumer
  expirationSeconds: 31536000
  includeJKS: true
  pkiBackendSpec:
    issuerRef:
      group: cert-manager.io
      kind: ClusterIssuer
      name: kafka-brokers-kafka-brokers-issuer
    pkiBackend: cert-manager
  secretName: testkube-consumer-secret
---
apiVersion: kafka.banzaicloud.io/v1alpha1
kind: KafkaUser
metadata:
  name: testkube-producer
  namespace: testkube
spec:
  clusterRef:
    name: kafka-brokers
    namespace: kafka-brokers
  createCert: true
  dnsNames:
  - testkube-producer
  expirationSeconds: 31536000
  includeJKS: true
  pkiBackendSpec:
    issuerRef:
      group: cert-manager.io
      kind: ClusterIssuer
      name: kafka-brokers-kafka-brokers-issuer
    pkiBackend: cert-manager
  secretName: testkube-producer-secret