apiVersion: broker.amq.io/v1beta1
kind: ActiveMQArtemisSecurity
metadata:
  name: ex-aao-prop
  namespace: activemq-artemis-brokers
spec:
  loginModules:
    guestLoginModules:
    - guestRole: guest
      guestUser: guest
      name: guest
    propertiesLoginModules:
    - name: PropertiesLoginModule
      users:
      - name: amq
        password: amq
        roles:
        - amq
      - name: cms
        password: cms
        roles:
        - cms
      - name: cgi
        password: cgi
        roles:
        - amq
  securityDomains:
    brokerDomain:
      loginModules:
      - flag: required
        name: PropertiesLoginModule
      name: activemq
  securitySettings:
    broker:
    - match: '#'
      permissions:
      - operationType: createDurableQueue
        roles:
        - amq
      - operationType: createNonDurableQueue
        roles:
        - amq
      - operationType: deleteDurableQueue
        roles:
        - amq
      - operationType: deleteNonDurableQueue
        roles:
        - amq
      - operationType: send
        roles:
        - amq
      - operationType: consume
        roles:
        - amq
      - operationType: manage
        roles:
        - amq
      - operationType: browse
        roles:
        - amq
      - operationType: createAddress
        roles:
        - amq
      - operationType: deleteAddress
        roles:
        - amq
    management:
      authorisation:
        defaultAccess:
        - method: list*
          roles:
          - amq
          - cms
        - method: get*
          roles:
          - amq
          - cms
        - method: is*
          roles:
          - amq
        - method: set*
          roles:
          - amq
        - method: '*'
          roles:
          - amq
